import ubinascii
import gc
from lib.epd2in13_V4 import EPD_2in13_V4_Landscape

# --- Configuration ---
# 브라우저(index.html)에서 생성하는 캔버스 스펙
# JS 기준 캔버스: 250 x 128 (상단 122라인만 실제 표시 영역)
CANVAS_WIDTH = 250
CANVAS_HEIGHT = 128
VISIBLE_HEIGHT = 122  # e-ink에서 실제로 사용하는 높이
BYTES_PER_ROW = (CANVAS_WIDTH + 7) // 8  # 250px -> 32바이트
img_hex = "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff3ffffffffffffffffffffffffffffffffffffffffffffffe0fffffffffffffff3fe3fffffffffffffffffffffffffffffffffffffffffff807ffffffffff3fff3fe3fffffffffffffffffffffffffffffffffffffffffff0f7fffffffffe3fff3fffffffffffffffffffffffffffffffffffffffffffffe1fffffffffffe3fff3fffffffffffffffffffffffffffffffffffffffffffffe3fe0381c0381c0f0300e3ffffffffffffffffffffffffffffffffffffffffffe3fe03818c710c0e0300e3ffffffffffffffffffffffffffffffffffffffffffe3fff18f9c63ce3c7f3ce3ffffffffffffffffffffffffffffffffffffffffffe3fff19f9c67ce3c7f3ce3ffffffffffffffffffffffffffffffffffffffffffe3ff819f80e7c63cff3ce3ffffffffffffffffffffffffffffffffffffffffffe3fe019f81e7c63cff3ce3ffffffffffffffffffffffffffffffffffffffffffe3fe719f9fe7ce3cff3ce3fffffffffffffffffffffffffffffffffffffffffff1fe719f80638e3c7f3ce3fffffffffffffffffffffffffffffffffffffffffff006019f80300f0e033ce3fffffffffffffffffffffffffffffffffffffffffffc06019f1e383f0f033ce3ffffffffffffffffffffffffffffffffffffffffffffffffff3e3fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff007fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff80ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc000000000000000000000000000000000000000000000000000000000ffffffc000000000000000000000000000000000000000000000000000000000fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe03fc3f80ffff87c07e01fff1fffc01fc03800f807ffffffffffffffffffffffc01f03f007ffe07801e00ffe1fffc01f803800f003ffffffffffffffffffffff820e03e083ffc078c1e007fe1fffc01f003800e0c3ffffffffffffffffffffff0f8e03e3e1ffc07fe1ff87fc1fffcffe1ffff0e3e1ffffffffffffffffffffff1f87c3c3e1fff87ff0ffc7f81fffcffe1ffff1c3e1ffffffffffffffffffffff1f87c3c7f1fff87ff0ffc7f01fff8ffe3fffe1e3e1ffffffffffffffffffffff1fc7c3c7f1fff87ff1ff87f01fff85fc3fffe1e1c3fffffffffffffffffffffe1fc7c3c7f1fff87fe1f80fe11fff803c007fe3f007fffffffffffffffffffffe1fc7c3c7f0fff87fe1f81fc31fff801c003fc3f80ffffffffffffffffffffffe1fc7c3c7f0c0387fc3f80fc71f019e0c1c1fc7f003fffffffffffffffffffffe1fc7c3c7f1c0387f87ff878f1f01ff0c3e1f87e1c1ffffffffffffffffffffff1fc7c3c7f1c0387f0fffc30f1f01ff8c3f1f87c3e1ffffffffffffffffffffff1f87c3c7f1fff87e1fffc30003ffff8c3f1f0fc7f1ffffffffffffffffffffff0f87c3c3e1fff87c1fffc30003ffff0e3e1f0fc7f1ffffffffffffffffffffff0f0fc3e3e1fff8783fff870007ffbe0e1e1f1fc3e1ffffffffffffffffffffff800fc3e003fff87800c007ff1fff801e003e1fe0c1ffffffffffffffffffffffc01fc3f007fff87000c00fff1fff003f007e1fe003ffffffffffffffffffffffe07fc3f80ffff87000e01fff1fffc07fc0fc3ff80fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7ffeffffbf87ff003e7cfff7ff9ffffffffffffffffffffffffffffffffffe037f7eff83bfffffe3f81ceff7019fffffffffffffffffffffffffffffffffffdf7f7eff79bc00ffe3fbdceff73f9fffffffffffffffffffffffffffffffffffcf1f7efe79bf8fffc9f3cceff73f9fffffffffffffffffffffffffffffffffff8f1f7efe7dbc31fe1c3bcceff73f9fffffffffffffffffffffffffffffffffff277f3eff79b8fcff7fb99ceff73f87fffffffffffffffffffffffffffffffffe737e3eff03b8007e001c3ceff73f87fffffffffffffffffffffffffffffffffcfb7e9effc7b8007e001fffeff73f9ffffffffffffffffffffffffffffffffffffffcceffefbfcffff7fefdeff73f9fffffffffffffffffffffffffffffffffff8079e6ffcfbc01ff80fcfce017009fffffffffffffffffffffffffffffffffffbf7bfefe00bffdff3e7c00e1f7839fffffffffffffffffffffffffffffffffffbf7ffeffffbc01ff7f3cfcfff7ff9dffffffffffffffffffffffffffffffffffbf7ffeffffbdffff3e7cfcfff7ff9dffffffffffffffffffffffffffffffffff807ffeffffbc00ff80fe00fff7ff9ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"

def update_display_from_buffer():
    """
    index.html 에서 생성한 Hex 문자열(가로 250, 세로 128, 1bpp)을
    FrameBuffer 기반 e-ink 버퍼로 다시 렌더링해서 출력합니다.

    - JS 쪽 비트 의미: 1 = 흰색, 0 = 검정
    - FrameBuffer(epd.pixel) 색상: 1 = 흰색, 0 = 검정  => 그대로 매핑
    """
    hex_data = img_hex
    print("Processing image data...")

    try:
        src = ubinascii.unhexlify(hex_data)
        src_len = len(src)
        print("Received data length:", src_len, "bytes")

        min_len = BYTES_PER_ROW * VISIBLE_HEIGHT
        if src_len < min_len:
            print("Error: Buffer too short (", src_len, "). Expected at least", min_len)
            return

        # e-ink 초기화
        epd = EPD_2in13_V4_Landscape()
        epd.init()
        # 흰색으로 전체 초기화
        epd.fill(1)

        # JS → FrameBuffer 좌표/비트 매핑
        # JS: row-major, 가로 8px 당 1바이트 (MSB = 왼쪽 픽셀)
        # src 인덱스: y * BYTES_PER_ROW + (x // 8)
        # bit 마스크: 0x80 >> (x % 8)
        for y in range(VISIBLE_HEIGHT):       # 0 ~ 121
            for x in range(CANVAS_WIDTH):     # 0 ~ 249
                byte_index = y * BYTES_PER_ROW + (x // 8)
                bit = x % 8
                mask = 0x80 >> bit

                is_white = 1 if (src[byte_index] & mask) else 0  # 1=white, 0=black
                epd.pixel(x, y, is_white)

        print("Sending buffer to display...")
        epd.display(epd.buffer)
        print("Putting display to sleep")
        epd.sleep()

        del epd
        del src
        gc.collect()

    except Exception as e:
        print("Display Error:", e)

if __name__ == "__main__":
    update_display_from_buffer()